### ISSUE TITLE
程序没有运行成功，新手！还请指教

### ISSUE THREAD

**Issue by lanhuaguizha** [zmrenwu/toutiao#3]
![20180827182102990](https://user-images.githubusercontent.com/9106780/44654995-31748880-aa26-11e8-827f-ca8cb2d52196.png)

**Comment by zmrenwu** [comment]
由于这个脚本编写的时间比较久远，头条的页面可能已经改变，源码只供参考，提供思路，可能已经无法达到预期效果了。

**Comment by lanhuaguizha** [comment]
好的。我找Rom组的同事看下^^，昨天他大概看了下。他们负责发版，一直摆弄Python写脚本，如果有答案。我再贴出来
